name: linter
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install
        run: make install

      - name: autoload
        run: make autoload

      - name: check linter
        run: make lint
